#! /bin/bash

echo "
envs_dirs:
  - /home/jovyan/my-conda-envs/
" > ~/.condarc

mkdir ~/collections

cd /etc/proxy/

node app.js & fusedav http://localhost:3000/api/v1/webdav/ ~/collections & jupyterhub-singleuser
